imports:
    - { resource: "services.yml" }

framework:
    translator: { fallback: en }
    templating:
        engines: ['twig']

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
