services:
    _defaults:
        autowire: true
        autoconfigure: true

    Abienvenu\KyjoukanBundle\Service\:
        resource: '../../Service/*'

    Abienvenu\KyjoukanBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
