services:
    Abienvenu\KyjoukanBundle\Service\:
        resource: '../../Service/*'

    Abienvenu\KyjoukanBundle\Service\DispatcherService:
        arguments: ['@doctrine.orm.entity_manager', '@Abienvenu\KyjoukanBundle\Service\RankService']

    Abienvenu\KyjoukanBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
