services:
    kyjoukan.dispatcher:
        class: Abienvenu\KyjoukanBundle\Service\DispatcherService
        arguments: ["@doctrine.orm.entity_manager"]

    kyjoukan.checker:
        class: Abienvenu\KyjoukanBundle\Service\CheckService

    kyjoukan.ranker:
        class: Abienvenu\KyjoukanBundle\Service\RankService
