doctrine:
    dbal:
        driver:   pdo_sqlite
        path: '%kernel.root_dir%/../data/kyjoukan.db3'
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
