<?php

namespace Abienvenu\KyjoukanBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroundRepository extends EntityRepository
{
}
