<?php

namespace Abienvenu\KyjoukanBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoolRepository extends EntityRepository
{
}
